#version: "3.8"

services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
      - nginx_certs:/etc/nginx/ssl
    networks:
      - inception
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress

networks:
  inception:
    name: inception

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/manuel/data/database
  web:
    name: web
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/manuel/data/web
  nginx_certs:
    name: cert
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/manuel/data/certs
