version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /home/manufern/data/web:/var/www/html
    networks:
      inception:
    restart: always

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - /home/manufern/data/web:/var/www/html
    networks:
      inception:
    restart: always

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - /home/manufern/data/database:/var/lib/mysql
    networks:
      inception:
    restart: always

networks:
  inception:
